---

- name: Post configuration
  hosts: all
  remote_user: root
  tags: post_setup
  gather_facts: yes

  roles:
    - post_setup

- name: Rebooting host
  hosts: all
  become: no
  remote_user: vagrant
  gather_facts: yes

  roles:
    - reboot
