---
# This playbook deploys the whole application stack in this site.

- import_playbook: common.yml

- name: Deploy LAMP configuration
  hosts: all
  remote_user: root
  tags: lamp
  gather_facts: yes

  tasks:
    - include_role: name=db
    - include_role: name=lamp

- import_playbook: post.yml
