---

- name: Removing old package Sendmail
  yum: name=sendmail state=absent

- name: Removing vagrant user...
  user:
    name: vagrant
    state: absent

- name: Removing vagrant group...
  user:
    name: vagrant
    state: absent

- name: Removing vagrant directory...
  file:
    path: /home/vagrant/
    state: absent

- name: Removing vagrant directory...
  file:
    path: /vagrant/
    state: absent

